



export const ADD_FAVORITE_SERVICE: 'ADD_FAVORITE_SERVICE' = 'ADD_FAVORITE_SERVICE';
export const UPLOAD_FAVORITE_SERVICE: 'UPLOAD_FAVORITE_SERVICE' = 'UPLOAD_FAVORITE_SERVICE';
export const DELETE_FAVORITE_SERVICE: 'DELETE_FAVORITE_SERVICE' = 'DELETE_FAVORITE_SERVICE';
export const SET_INITIAL_FAVORITE_SERVICE: 'SET_INITIAL_FAVORITE_SERVICE' = 'SET_INITIAL_FAVORITE_SERVICE';
export const SET_FAVORITE_FLAGS: 'SET_FAVORITE_FLAGS' = 'SET_FAVORITE_FLAGS';